### ISSUE TITLE
DM does not work with this plugin

### ISSUE THREAD

**Issue by youtsumi** [kaakaa/mattermost-plugin-sharepost#4]
Everyday in the morning gitlab plugin (https://github.com/mattermost/mattermost-plugin-gitlab) summarizes todos such as unread messages, review requests, assignments, your open merge requests and sends out the summary to a user in DM. However it has started to fail since this sharepost plugin is enabled with the following error messages:

> {"level":"error","ts":1588690851.7369776,"caller":"mlog/sugar.go:23","msg":"can't post DM","plugin_id":"com.github.manland.mattermost-plugin-gitlab","err":""}> 
> {"level":"error","ts":1588690851.7372928,"caller":"mlog/sugar.go:23","msg":"can't create dm post in post todo","plugin_id":"com.github.manland.mattermost-plugin-gitlab","err":""}

If I disable the sharepost plugin, then GitLab plugin succeeds to send the summary out in DM.

**Comment by youtsumi** [comment]
I notice that the DM feature doesn't work with this plugin enabled. This is not an issue with gitlab. This is an example of log message:

> {"level":"error","ts":1589166412.8768935,"caller":"mlog/log.go:175","msg":"Post rejected by plugin. SqlTeamStore.Get: 既存のチームが見付かりませんでした。, id=","path":"/api/v4/posts","request_id":"j8sfxck6hjnfx8zqj977rqn8ah","ip_addr":"10.88.0.1","user_id":"u7cjj7ybhig8zfnjb75xbeqaja","method":"POST","err_where":"createPost","http_code":400,"err_details":""}

**Comment by kaakaa** [comment]
Fixed by #5
